"""Add password field

Revision ID: f8264676c887
Revises: 87e5f182b361
Create Date: 2020-04-27 11:31:50.462764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8264676c887'
down_revision = '87e5f182b361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("users") as batch_op:
           batch_op.drop_column('password')
    # op.drop_column('users', 'password')
