context_parser: pypyr.parser.list
steps:
  - name: pypyr.steps.call
    comment: lint と test これはすべてのパイプラインの起動時に実行される
    in:
      call:
        - lint
        - test
  - name: pypyr.steps.call
    comment: オプション lint と testの後に packageやpublish などを追加実行
    run: '{argList}'
    in:
      call: '{argList}'

lint:
  - name: pypyr.steps.cmd
    in:
      cmd: echo lint command here

test:
  - name: pypyr.steps.cmd
    in:
      cmd: echo test command here

package:
  - name: pypyr.steps.cmd
    in:
      cmd: echo package command here

publish:
  - name: pypyr.steps.cmd
    in:
      cmd: echo publish command here

